# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{evented-gearman-ruby}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kim Altintop"]
  s.date = %q{2010-07-19}
  s.description = %q{Library for the Gearman distributed job system}
  s.email = %q{kim.altintop@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README",
     "TODO"
  ]
  s.files = [
    ".gitignore",
     "HOWTO",
     "LICENSE",
     "README",
     "Rakefile",
     "TODO",
     "VERSION.yml",
     "examples/calculus_client.rb",
     "examples/calculus_worker.rb",
     "examples/client.rb",
     "examples/client_background.rb",
     "examples/client_data.rb",
     "examples/client_exception.rb",
     "examples/client_prefix.rb",
     "examples/evented_client.rb",
     "examples/evented_worker.rb",
     "examples/gearman_environment.sh",
     "examples/scale_image.rb",
     "examples/scale_image_worker.rb",
     "examples/server.rb",
     "examples/worker.rb",
     "examples/worker_data.rb",
     "examples/worker_exception.rb",
     "examples/worker_prefix.rb",
     "gearman-ruby.gemspec",
     "lib/gearman.rb",
     "lib/gearman/client.rb",
     "lib/gearman/evented/client.rb",
     "lib/gearman/evented/reactor.rb",
     "lib/gearman/evented/worker.rb",
     "lib/gearman/job.rb",
     "lib/gearman/protocol.rb",
     "lib/gearman/server.rb",
     "lib/gearman/task.rb",
     "lib/gearman/taskset.rb",
     "lib/gearman/util.rb",
     "lib/gearman/worker.rb",
     "test/basic_integration_test.rb",
     "test/crash_test.rb",
     "test/job_test.rb",
     "test/protocol_test.rb",
     "test/test_helper.rb",
     "test/util_test.rb",
     "test/worker_test.rb"
  ]
  s.homepage = %q{http://github.com/kim/evented-gearman-ruby}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{eventmachine-based library for the Gearman distributed job system}
  s.test_files = [
    "test/basic_integration_test.rb",
     "test/crash_test.rb",
     "test/job_test.rb",
     "test/protocol_test.rb",
     "test/test_helper.rb",
     "test/util_test.rb",
     "test/worker_test.rb",
     "examples/calculus_client.rb",
     "examples/calculus_worker.rb",
     "examples/client.rb",
     "examples/client_background.rb",
     "examples/client_data.rb",
     "examples/client_exception.rb",
     "examples/client_prefix.rb",
     "examples/evented_client.rb",
     "examples/evented_worker.rb",
     "examples/scale_image.rb",
     "examples/scale_image_worker.rb",
     "examples/server.rb",
     "examples/worker.rb",
     "examples/worker_data.rb",
     "examples/worker_exception.rb",
     "examples/worker_prefix.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<eventmachine>, [">= 0.12.8"])
    else
      s.add_dependency(%q<eventmachine>, [">= 0.12.8"])
    end
  else
    s.add_dependency(%q<eventmachine>, [">= 0.12.8"])
  end
end

